### ISSUE TITLE
Issues in deploying RHOBS on OCP cluster

### ISSUE THREAD

**Issue by vprashar2929** [rhobs/configuration#378]
Some issues observed while deploying RHOBS on OCP cluster using [launch script](https://github.com/rhobs/configuration/blob/main/tests/launch.sh)
1. Deployment script under the test folder gets failed while adding rules This happened when deploying `observatorium-template.yaml`.
2. Older image of `observatorium-api` is used in `observatorium-template.yaml` due to which `observatorium-api` remains in CrashLoopBackOff state.
3. Older image of Thanos is used in `observatorium-metrics-template.yaml` due to which `Thanos` remains in CrashLoopBackOff state.
4. The PVC which were supposed to be created in `observatorium-metrics-template.yaml` were all in pending state due to the `gp2` storage class not available on the OCP cluster.

**Comment by philipgough** [comment]
@vprashar2929 can we close this?

**Comment by vprashar2929** [comment]
yes sorry didn't close earlier😅
